# Generated by Django 3.1.1 on 2020-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField(null=True)),
                ('submission_date', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
