# Generated by Django 3.1.1 on 2020-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='submission_date',
        ),
    ]
