# Generated by Django 3.1.1 on 2020-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_remove_cookie_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
