# Generated by Django 3.1.1 on 2020-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_cookie_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='imagepath',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
